// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GreetMessage
	DateMessage
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreetMessage struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *GreetMessage) Reset()                    { *m = GreetMessage{} }
func (m *GreetMessage) String() string            { return proto.CompactTextString(m) }
func (*GreetMessage) ProtoMessage()               {}
func (*GreetMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GreetMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type DateMessage struct {
	Date string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
}

func (m *DateMessage) Reset()                    { *m = DateMessage{} }
func (m *DateMessage) String() string            { return proto.CompactTextString(m) }
func (*DateMessage) ProtoMessage()               {}
func (*DateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DateMessage) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetMessage)(nil), "api.GreetMessage")
	proto.RegisterType((*DateMessage)(nil), "api.DateMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ping service

type PingClient interface {
	CheckIn(ctx context.Context, in *GreetMessage, opts ...grpc.CallOption) (*GreetMessage, error)
	GetDate(ctx context.Context, in *DateMessage, opts ...grpc.CallOption) (*DateMessage, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) CheckIn(ctx context.Context, in *GreetMessage, opts ...grpc.CallOption) (*GreetMessage, error) {
	out := new(GreetMessage)
	err := grpc.Invoke(ctx, "/api.Ping/CheckIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) GetDate(ctx context.Context, in *DateMessage, opts ...grpc.CallOption) (*DateMessage, error) {
	out := new(DateMessage)
	err := grpc.Invoke(ctx, "/api.Ping/GetDate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingServer interface {
	CheckIn(context.Context, *GreetMessage) (*GreetMessage, error)
	GetDate(context.Context, *DateMessage) (*DateMessage, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).CheckIn(ctx, req.(*GreetMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_GetDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).GetDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/GetDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).GetDate(ctx, req.(*DateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _Ping_CheckIn_Handler,
		},
		{
			MethodName: "GetDate",
			Handler:    _Ping_GetDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xd2, 0xe2, 0xe2, 0x71, 0x2f,
	0x4a, 0x4d, 0x2d, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0x07,
	0xf1, 0x33, 0xf3, 0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25, 0x45, 0x2e,
	0x6e, 0x97, 0xc4, 0x92, 0x54, 0x98, 0x52, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x54, 0xa8, 0x32,
	0x30, 0xdb, 0x28, 0x8b, 0x8b, 0x25, 0x20, 0x33, 0x2f, 0x5d, 0xc8, 0x90, 0x8b, 0xdd, 0x39, 0x23,
	0x35, 0x39, 0xdb, 0x33, 0x4f, 0x48, 0x50, 0x0f, 0x64, 0x25, 0xb2, 0x25, 0x52, 0x98, 0x42, 0x4a,
	0x0c, 0x42, 0xfa, 0x5c, 0xec, 0xee, 0xa9, 0x25, 0x20, 0x0b, 0x84, 0x04, 0xc0, 0xf2, 0x48, 0x76,
	0x49, 0x61, 0x88, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xbd, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x9b, 0xcd, 0xb6, 0x44, 0xd3, 0x00, 0x00, 0x00,
}
